### ISSUE TITLE
Add TableFlow Template

### ISSUE THREAD

**Issue by ndneighbor** [railwayapp/templates#428]

**Comment by Aravindha1234u** [comment]
Will work on this.

**Comment by Aravindha1234u** [comment]
Hi 

Template: https://railway.app/template/Zj8toL
Repo: https://github.com/Aravindha1234u/tableflow-railway

I have added a known issues which describes about the scylladb since its not working ipv6 in railway network and other issue I am working on it

**Comment by melissa-hale** [comment]
Hi @Aravindha1234u !

I'm not able to get this working using the instructions, not sure where to go to see the UI, and the backend crashes on me.  I played around a bit with your version and poked around in the TableFlow source repo, but without spending a non-insignificant amount of time, I can't offer much in the way of helpful code snippets or pointers.

I can say though, if you need to be able to communicate to a DB within a service, and you can't use the private network, you may find the new [TCP Proxy feature helpful](https://railway.app/changelog/2023-09-08-regions#tcp-proxying-to-priority-boarding).  I know I mentioned before in Discord, but the community channels would be a really great resource from here.

As far as the program goes, I know you've been hard at work trying to get this one across the finish line, so I am happy to extend the deadline for this one submission while you work to get it polished.

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale 
Thank you for recommending TCP Proxy I have fixed Scylla db in the template. can you test again? but still, we have minor issues with importer-ui which I am trying to fix but it has to be fixed from tableflow source code.

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale 

Update: I have fixed the importer-ui as well and everything works as expected. Hope there is no more issues with this template.

**Comment by melissa-hale** [comment]
Hey @Aravindha1234u ! can you please elaborate in the docs on how to connect the backend to the scyla db?

> Deployment will take some time. Once scylla DB is deployed and running, you should get TCP proxy URL in settings -> public networking. Copy the URL and update the backend service environment variables and make sure to redeploy the service to make it work as expected.

You shouldn't actually need to do this because there are variables:  RAILWAY_TCP_PROXY_DOMAIN and RAILWAY_TCP_PROXY_PORT that you can use in the template.  So like ${{ scyla.RAILWAY_TCP_PROXY_DOMAIN }} for example.

Lastly, it's still not clear to me on how to access the UI - 
I see this: Access the Admin UI by navigating to "[http://\.up.railway.dev/](http://.up.railway.dev/)".
and this: Access the Admin UI by navigating to "http://<PROJECT_URL>.up.railway.dev/".

But not really sure what this is telling me ^.  Can I not just click on the domain of the backend service?

**Comment by Aravindha1234u** [comment]
HI @melissa-hale 
I have updated the railway template for Scylla DB host and port it's working. Also, I have updated README.md

Please take a look at it and keep me posted.
Thank you

**Comment by melissa-hale** [comment]
@Aravindha1234u for posterity - we're good on this one!  

Last request while you move things over (https://github.com/railwayapp-templates/tableflow-railway) - I am interested in seeing the specific details around why you chose to Fork the TableFlow repo included in the Overview. I'd like for people to understand the implementation of the template and how it differs from the original TableFlow repo.

Thanks!

**Comment by Aravindha1234u** [comment]
Hi @melissa-hale 

I have pushed changes and updated the railway template with the new repo as the source. Also, I have added an important notice to denote why we forked the repo in README.md. Let me know if any other change is required.
